---
deployment:
  tasks:
    - export DEPLOYPATH=/home/stallion/public_html/contact_us
    - /bin/cp -R * $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 755 {} \;